stages:
  - build
  # - deploy

build:
  stage: build
  image: node:latest
  before_script:
    - cd myMatch
  script:
    - echo "Building your application..."
    - npm install
    - npm run build

cache:
    paths:
      - myMatch/node_modules/
    

# deploy:
#   stage: deploy
#   script:
#     - echo "Deploying your application..."







